// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBksUUJm_BJ91qRCNtPmCCmHwPL29L1pPc',
    appId: '1:679489293788:web:4e73b6c55a71c723e09319',
    messagingSenderId: '679489293788',
    projectId: 'godfaild-ourproject',
    authDomain: 'godfaild-ourproject.firebaseapp.com',
    storageBucket: 'godfaild-ourproject.appspot.com',
    measurementId: 'G-14GSRE61BT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfeucm_o7d9ixsawJjOsiS6QyCUox_PaU',
    appId: '1:679489293788:android:c97c178b5abf4e97e09319',
    messagingSenderId: '679489293788',
    projectId: 'godfaild-ourproject',
    storageBucket: 'godfaild-ourproject.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBksUUJm_BJ91qRCNtPmCCmHwPL29L1pPc',
    appId: '1:679489293788:web:6947944458999781e09319',
    messagingSenderId: '679489293788',
    projectId: 'godfaild-ourproject',
    authDomain: 'godfaild-ourproject.firebaseapp.com',
    storageBucket: 'godfaild-ourproject.appspot.com',
    measurementId: 'G-W8W5LD7L4L',
  );
}
